name: Slack Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "#channel" # 알림을 받을 Slack 채널
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # GitHub Secrets에 저장된 Slack Webhook URL
          MESSAGE: "Deployment to production is complete!"
